name: allure-junit5-maven

on: [ push ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run Test
        if: always()
        run: mvn package
        continue-on-error: true
